server:
  port: 10086
xxl:
  job:
    admin:
      addresses: http://192.168.200.130:8888/xxl-job-admin
    executor:
      appname: dlut-library-schedule
      port: 8989
dlut:
  reserveUser:
    user1:
      username:
      password:
  wantedSeats:
    - 140
    - 141
    - 142
    - 143
    - 144
  library:
    bochuan:
      code: 17
      rooms:
        301: 168
        312: 170
        401: 195
        404: 197
        409: 196
        501: 198
        504: 199
        507: 200
    lingxi:
      code: 32
      rooms:
        301: 207
        302: 208
        401: 205
        402: 206
        501: 203
        502: 204
        601: 201
        602: 202
        202: 242